import { INSTITUTE_LOGO } from './education';
import { COMPANIES_LOGO } from './experience';
import { TECHNOLOGIES_ICONS } from './technologies';
import AALogo from '../assets/images/AA-logo-white.webp';

const ROLE = {
  BE: 'Backend Developer',
  FE: 'Frontend Developer',
  FS: 'Fullstack Developer',
};

const PROJECTS = [
  {
    title: 'TrueNorth Gym',
    year: 2026,
    liveDemoUrl: 'https://truenorthgym.nl/en',
    githubUrl: null,
    description: [
      'A bilingual (English/Dutch) fitness website built with Next.js and the App Router, giving members an easy way to explore workout programs, training resources, and wellness content.',
      "Designed and developed the site end-to-end, running multiple rounds of discussions with the gym's owner to understand the required capabilities before design began, with SEO as a key priority given how much local discovery matters for the business.",
      'Implemented internationalized routing and a shared design-token system for consistent theming across locales, styled with Tailwind CSS.',
      'Optimized for Core Web Vitals and Lighthouse performance, with improved SEO metadata and Open Graph image generation for better discoverability and link previews.',
      'Deployed on Cloudflare, with a clean, accessible, performance-optimized design ensuring fast page loads and smooth interactions across desktop and mobile devices.',
      "Integrated with Virtual Gym's SDKs, the platform the owner uses to manage member details, keeping the website in sync with day-to-day gym operations.",
    ],
    techStack: {
      languages: [TECHNOLOGIES_ICONS.TYPESCRIPT],
      frontend: [TECHNOLOGIES_ICONS.TAILWIND, TECHNOLOGIES_ICONS.NEXTJS],
      backend: [],
      tools: [
        TECHNOLOGIES_ICONS.GIT,
        TECHNOLOGIES_ICONS.CLAUDE_CODE,
        TECHNOLOGIES_ICONS.CODEX,
      ],
    },
    partnerLogo: AALogo,
    under: 'Amadhya Anand',
    role: ROLE.FE,
  },
  {
    title: 'CSV Processing System',
    year: 2026,
    liveDemoUrl: null,
    githubUrl: null,
    description: [
      'An event-driven, serverless system built on AWS to replace a legacy cron-based CSV ingestion pipeline, reducing processing time for 500K-entry files from 10 hours to 26 minutes.',
      'Investigated legacy tooling owned by the team and a sister team, led architecture discussions with stakeholders, and documented the proposed design in an RFC before implementation began.',
      'Delivered iteratively across separate UI and backend phases, enabling early feedback and course correction throughout the build.',
      'Built as a generic platform so multiple products and teams can onboard independently, using a config-driven (YAML) schema and a Claude-powered command that guides new products through setup in minutes.',
      "Includes a config-driven UI layer — the frontend dynamically renders forms and views based on a product's YAML schema, removing the need for custom frontend work per product.",
      'Built Grafana dashboards tracking the health of every service in the pipeline, alongside uploaded file sizes, batch/grouping sizes, and performance at both the per-service and system-wide level.',
      'Added an audit system that detected stale files in the pipeline and triggered alerts before they became a problem.',
      'Used Claude to generate unit tests across the codebase, raising coverage without slowing delivery.',
    ],
    techStack: {
      languages: [TECHNOLOGIES_ICONS.TYPESCRIPT, TECHNOLOGIES_ICONS.JAVA],
      frontend: [],
      backend: [
        TECHNOLOGIES_ICONS.AWS_LAMBDA,
        TECHNOLOGIES_ICONS.SQS,
        TECHNOLOGIES_ICONS.DYNAMODB,
      ],
      tools: [],
    },
    partnerLogo: COMPANIES_LOGO.BOOKING,
    under: 'Booking.com',
    role: ROLE.FS,
  },
  {
    title: 'Portfolio',
    year: 2025,
    liveDemoUrl: 'https://amadhya-portfolio.web.app',
    githubUrl: 'https://github.com/amadhya02/Portfolio',
    description: [
      'A custom-built developer portfolio — engineered from scratch with React, MUI, and Framer Motion, with scroll-driven parallax throughout and full support for reduced-motion preferences.',
      'Audited and rebuilt for performance: converted every image to WebP, cutting total page weight by over 90%, and eliminated layout shift entirely by restructuring how routes load — moving Lighthouse performance scores from the 40s into the 80s and 90s across every page.',
      'Built as a small design system rather than one-off pages — shared components and a parallax-scroll hook keep the visual language and interaction patterns consistent across every section.',
      'Fixed real accessibility gaps: heading-order violations and a case where an overriding aria-label was hiding visible button content from screen readers.',
      'Consolidated SEO end-to-end — unified meta descriptions across search, social, and structured data, and removed duplicate JSON-LD schema that was rendering twice on the homepage.',
    ],
    techStack: {
      languages: [TECHNOLOGIES_ICONS.JAVASCRIPT],
      frontend: [
        TECHNOLOGIES_ICONS.CSS,
        TECHNOLOGIES_ICONS.MATERIAL_UI,
        TECHNOLOGIES_ICONS.REACT,
        TECHNOLOGIES_ICONS.REACT_ROUTER,
      ],
      backend: [],
      tools: [
        TECHNOLOGIES_ICONS.FIGMA,
        TECHNOLOGIES_ICONS.GIT,
        TECHNOLOGIES_ICONS.CLAUDE_CODE,
      ],
    },
    partnerLogo: AALogo,
    under: 'Amadhya Anand',
    role: ROLE.FE,
  },
  {
    title: 'Developer Data Collector',
    year: 2025,
    liveDemoUrl: null,
    githubUrl: null,
    description: [
      'A Python-based CLI tool that aggregates and reports developer activity and code quality metrics across GitLab, Jira, and SonarQube for a specified time period.',
      'Parses merged merge requests from multiple GitLab instances, capturing detailed stats such as additions, deletions, and file changes.',
      'Detects documentation contributions by identifying updates to README.md files in committed changes.',
      'Calculates test coverage trends by analyzing the proportion of test files among all modified files per user and per project.',
      'Integrates with SonarQube to retrieve and categorize assigned code quality issues by severity and type, offering a comprehensive view of technical debt.',
      'Tracks GitLab user activity events (pushes, comments, merges, etc.) to provide behavioral insights and engagement patterns.',
      'Queries Jira to count the number of tasks and bugs taken up by the user, broken down by project and issue type.',
      'Monitors Jira Wiki contributions, tracking how many pages the user has authored or edited.',
    ],
    techStack: {
      languages: [TECHNOLOGIES_ICONS.PYTHON],
      frontend: [],
      backend: [],
      tools: [
        TECHNOLOGIES_ICONS.GITLAB,
        TECHNOLOGIES_ICONS.JIRA,
        TECHNOLOGIES_ICONS.SONARQUBE,
      ],
    },
    partnerLogo: COMPANIES_LOGO.BOOKING,
    under: 'Booking.com',
    role: ROLE.BE,
  },
  {
    title: 'Metro Atlanta Saves',
    year: 2024,
    liveDemoUrl: 'https://www.brpatl.com/',
    githubUrl: null,
    description: [
      'MetroAtlantaSaves is a financial wellness platform built to help residents in the Atlanta area set and achieve savings goals.',
      'Users can create profiles, define savings objectives, and track their progress through guided financial programs.',
      'The platform includes key pages like About Us, Blogs, Educational Resources, and a Savings Calculator to support user learning and engagement.',
      'An admin dashboard allows authorized users to manage dynamic forms, review user data, and monitor engagement metrics.',
      'The frontend is built using React, offering a clean and responsive interface.',
      'The backend uses Express and Prisma, with PostgreSQL as the primary database.',
      'Docker is used for containerization, with deployment handled through PM2 and Nginx.',
      'The site is secured with Let’s Encrypt SSL and runs on a DigitalOcean VM.',
    ],
    techStack: {
      languages: [TECHNOLOGIES_ICONS.TYPESCRIPT],
      frontend: [
        TECHNOLOGIES_ICONS.REACT,
        TECHNOLOGIES_ICONS.REACT_ROUTER,
        TECHNOLOGIES_ICONS.CSS,
      ],
      backend: [
        TECHNOLOGIES_ICONS.NODEJS,
        TECHNOLOGIES_ICONS.EXPRESS,
        TECHNOLOGIES_ICONS.POSTGRESQL,
      ],
      tools: [
        TECHNOLOGIES_ICONS.GIT,
        TECHNOLOGIES_ICONS.DOCKER,
        TECHNOLOGIES_ICONS.NGINX,
      ],
    },
    partnerLogo: INSTITUTE_LOGO.GA_TECH,
    under: 'Georgia Tech',
    role: ROLE.FS,
  },
  {
    title: 'Alcohol Tracker',
    year: 2023,
    liveDemoUrl: null,
    githubUrl: null,
    description: [
      'This health analytics platform was developed to help users track their alcohol consumption and its correlation with health conditions.',
      'Users could log their drinking habits, health issues, and duration of illness through a clean and interactive interface.',
      'The system compared user data with insights from a comprehensive research dataset on alcohol consumption and health impacts.',
      'It highlighted common patterns, symptoms, and diseases based on age groups and usage trends.',
      'The project offered visual comparisons to show users how their consumption relates to broader data, helping raise awareness of potential health risks.',
      'This was a collaborative group project focused on promoting health literacy through data-driven insights.',
    ],
    techStack: {
      languages: [TECHNOLOGIES_ICONS.JAVASCRIPT, TECHNOLOGIES_ICONS.D3],
      frontend: [
        TECHNOLOGIES_ICONS.REACT,
        TECHNOLOGIES_ICONS.CSS,
        TECHNOLOGIES_ICONS.REACT_ROUTER,
      ],
      backend: [
        TECHNOLOGIES_ICONS.NODEJS,
        TECHNOLOGIES_ICONS.EXPRESS,
        TECHNOLOGIES_ICONS.MY_SQL,
      ],
      tools: [TECHNOLOGIES_ICONS.GIT, TECHNOLOGIES_ICONS.DOCKER],
    },
    partnerLogo: INSTITUTE_LOGO.GA_TECH,
    under: 'Georgia Tech',
    role: ROLE.FS,
  },
  {
    title: 'ATS Website',
    year: 2023,
    liveDemoUrl: 'https://aerialtelecom.in/',
    githubUrl: null,
    description: [
      'Developed a modern, responsive corporate website for Aerial Telecom Solutions (ATS), a key player in telecom infrastructure and training services, as freelance work.',
      'Built from a design created by another designer — reviewed closely in Figma, with ideas and feedback shared throughout the process.',
      'The platform highlights ATS’s service offerings, organizational impact, and legacy with a clean and accessible user interface.',
      'Focused on performance, accessibility, and stakeholder engagement, the site includes subtle animations, a structured content flow, and an intuitive navigation system optimized for desktop and mobile devices.',
      'Optimized the site for SEO with structured metadata and clean semantic markup, helping ATS get discovered by prospective clients and partners searching for telecom infrastructure and training services.',
    ],
    techStack: {
      languages: [TECHNOLOGIES_ICONS.JAVASCRIPT],
      frontend: [
        TECHNOLOGIES_ICONS.CSS,
        TECHNOLOGIES_ICONS.MATERIAL_UI,
        TECHNOLOGIES_ICONS.REACT,
        TECHNOLOGIES_ICONS.REACT_ROUTER,
      ],
      backend: [],
      tools: [TECHNOLOGIES_ICONS.FIGMA, TECHNOLOGIES_ICONS.GIT],
    },
    partnerLogo: COMPANIES_LOGO.ATS,
    under: 'Aerial Telecom Solutions',
    role: ROLE.FE,
  },
  {
    title: 'Game Swap',
    year: 2022,
    liveDemoUrl: null,
    githubUrl: null,
    description: [
      'Game Swap is a community-driven platform designed to facilitate the exchange of video games among users, reducing waste and promoting game accessibility.',
      'Users can list their games for swapping, search through listings using various filters, and initiate a swap request for items they’re interested in.',
      'Each swap request can be accepted or declined by the receiver, and once completed, users can leave ratings for transparency and reliability.',
      'A personal dashboard allows users to manage their listings, monitor swap status, and review their full swap history for easy reference.',
    ],
    techStack: {
      languages: [TECHNOLOGIES_ICONS.JAVASCRIPT, TECHNOLOGIES_ICONS.PYTHON],
      frontend: [
        TECHNOLOGIES_ICONS.CSS,
        TECHNOLOGIES_ICONS.MATERIAL_UI,
        TECHNOLOGIES_ICONS.REACT,
        TECHNOLOGIES_ICONS.REACT_ROUTER,
      ],
      backend: [TECHNOLOGIES_ICONS.FLASK, TECHNOLOGIES_ICONS.MY_SQL],
      tools: [TECHNOLOGIES_ICONS.GIT, TECHNOLOGIES_ICONS.DOCKER],
    },
    partnerLogo: INSTITUTE_LOGO.GA_TECH,
    under: 'Georgia Tech',
    role: ROLE.FS,
  },
  {
    year: 2020,
    title: 'SwyftCart E-commerce',
    githubUrl: null,
    under: 'SwyftCart',
    description: [
      'Built a full-fledged e-commerce web application that allows users to explore products from multiple nearby shops and purchase them seamlessly.',
      'Implemented key features such as cart management, online and COD payment options, order tracking, and cancellation functionality.',
      'Designed the system with user convenience in mind, ensuring responsive layouts, optimized load times, and secure user sessions.',
    ],
    techStack: {
      languages: [TECHNOLOGIES_ICONS.TYPESCRIPT],
      frontend: [
        TECHNOLOGIES_ICONS.CSS,
        TECHNOLOGIES_ICONS.ANTD,
        TECHNOLOGIES_ICONS.REACT,
        TECHNOLOGIES_ICONS.REACT_ROUTER,
      ],
      backend: [
        TECHNOLOGIES_ICONS.EXPRESS,
        TECHNOLOGIES_ICONS.FIREBASE,
        TECHNOLOGIES_ICONS.NODEJS,
      ],
      tools: [TECHNOLOGIES_ICONS.FIGMA, TECHNOLOGIES_ICONS.GIT],
    },
    partnerLogo: AALogo,
    role: ROLE.FS,
  },
  {
    year: 2020,
    title: 'SwyftCart Admin',
    githubUrl: null,
    under: 'SwyftCart',
    description: [
      'Developed the administrative interface for shop owners using the SwyftCart platform to manage their business operations effectively.',
      'The dashboard provides comprehensive access to product and inventory management, order tracking, analytics, and fulfillment tools.',
      'Built with a focus on simplicity and control, the interface allows real-time updates to product listings and efficient status handling of customer orders.',
    ],
    techStack: {
      languages: [TECHNOLOGIES_ICONS.TYPESCRIPT],
      frontend: [
        TECHNOLOGIES_ICONS.CSS,
        TECHNOLOGIES_ICONS.ANTD,
        TECHNOLOGIES_ICONS.REACT,
        TECHNOLOGIES_ICONS.REACT_ROUTER,
      ],
      backend: [
        TECHNOLOGIES_ICONS.EXPRESS,
        TECHNOLOGIES_ICONS.FIREBASE,
        TECHNOLOGIES_ICONS.NODEJS,
      ],
      tools: [TECHNOLOGIES_ICONS.FIGMA, TECHNOLOGIES_ICONS.GIT],
    },
    partnerLogo: AALogo,
    role: ROLE.FS,
  },
  {
    year: 2019,
    title: 'Suvidham',
    liveDemoUrl: 'http://suvidham.now.sh/',
    githubUrl: 'https://github.com/amadhya02/Shighram',
    under: 'Punjab Engineering College',
    description: [
      'Created a smart parking management system consisting of a responsive web interface and an Android application.',
      'Users can register or authenticate via Google, check real-time parking slot availability, make payments digitally, and view transaction history.',
      'The application streamlines urban parking challenges by providing a user-friendly interface and secure payment workflows, making it practical for campus or city-level deployments.',
    ],
    techStack: {
      languages: [
        TECHNOLOGIES_ICONS.CPP,
        TECHNOLOGIES_ICONS.JAVASCRIPT,
        TECHNOLOGIES_ICONS.KOTLIN,
        TECHNOLOGIES_ICONS.PYTHON,
      ],
      frontend: [
        TECHNOLOGIES_ICONS.CSS,
        TECHNOLOGIES_ICONS.MATERIAL_UI,
        TECHNOLOGIES_ICONS.REACT,
        TECHNOLOGIES_ICONS.REACT_ROUTER,
      ],
      backend: [TECHNOLOGIES_ICONS.DJANGO, TECHNOLOGIES_ICONS.MY_SQL],
      tools: [TECHNOLOGIES_ICONS.GIT],
    },
    partnerLogo: INSTITUTE_LOGO.PEC,
    role: ROLE.FS,
  },
  {
    year: 2019,
    title: 'Patralaya',
    githubUrl: 'https://github.com/amadhya02/Patralaya',
    under: 'Punjab Engineering College',
    description: [
      'Built a feature-rich blogging platform enabling users to create, categorize, and tag posts for organized content distribution.',
      'The platform allows readers to browse blogs, filter feeds based on categories or tags, and view author profiles.',
      'Implemented social media sharing for broader reach and integrated user-friendly navigation with clean visual hierarchy.',
    ],
    techStack: {
      languages: [TECHNOLOGIES_ICONS.JAVASCRIPT, TECHNOLOGIES_ICONS.PYTHON],
      frontend: [
        TECHNOLOGIES_ICONS.CSS,
        TECHNOLOGIES_ICONS.MATERIAL_UI,
        TECHNOLOGIES_ICONS.REACT,
        TECHNOLOGIES_ICONS.REACT_ROUTER,
      ],
      backend: [TECHNOLOGIES_ICONS.DJANGO, TECHNOLOGIES_ICONS.POSTGRESQL],
      tools: [TECHNOLOGIES_ICONS.GIT],
    },
    partnerLogo: INSTITUTE_LOGO.PEC,
    role: ROLE.FS,
  },
  {
    year: 2019,
    title: 'Chatroom',
    githubUrl: 'https://github.com/EightBitGod/TheDevCom_ProjectChatroom',
    under: 'Amadhya Anand',
    description: [
      'Collaboratively developed a real-time chat application designed to support multi-user communication within rooms.',
      'Implemented features such as emoji support, user presence tracking (online/last seen), and message timestamping.',
      'Focused on team collaboration, backend efficiency, and responsive chat interface design, enabling smooth real-time interaction among users.',
    ],
    techStack: {
      languages: [TECHNOLOGIES_ICONS.JAVASCRIPT, TECHNOLOGIES_ICONS.PYTHON],
      frontend: [
        TECHNOLOGIES_ICONS.CSS,
        TECHNOLOGIES_ICONS.MATERIAL_UI,
        TECHNOLOGIES_ICONS.REACT,
        TECHNOLOGIES_ICONS.REACT_ROUTER,
      ],
      backend: [TECHNOLOGIES_ICONS.DJANGO, TECHNOLOGIES_ICONS.REDIS],
      tools: [TECHNOLOGIES_ICONS.GIT],
    },
    partnerLogo: AALogo,
    role: ROLE.FS,
  },
];

export default PROJECTS;
