import React from 'react';

export const TECHNOLOGIES_ICONS = {
  ANTD: { Icon: 'devicon-antdesign-plain', text: 'Ant Design' },
  AWS_LAMBDA: {
    Icon: 'devicon-amazonwebservices-plain-wordmark',
    text: 'AWS Lambda',
  },
  CPP: { Icon: 'devicon-cplusplus-plain', text: 'C++' },
  CSS: { Icon: 'devicon-css3-plain', text: 'CSS3' },
  D3: { Icon: 'devicon-d3js-plain', text: 'D3.js' },
  DJANGO: { Icon: 'devicon-django-plain', text: 'Django' },
  DOCKER: { Icon: 'devicon-docker-plain', text: 'Docker' },
  DROPWIZARD: { Icon: 'devicon-dropwizard-plain', text: 'Dropwizard' },
  ELASTIC_SEARCH: {
    Icon: 'devicon-elasticsearch-plain',
    text: 'ElasticSearch',
  },
  ESLINT: { Icon: 'devicon-eslint-plain', text: 'ESLint' },
  EXPRESS: { Icon: 'devicon-express-original', text: 'Express.js' },
  FIGMA: { Icon: 'devicon-figma-plain', text: 'Figma' },
  FIREBASE: { Icon: 'devicon-firebase-plain', text: 'Firebase' },
  FLASK: { Icon: 'devicon-flask-original', text: 'Flask' },
  GIT: { Icon: 'devicon-git-plain', text: 'Git' },
  GITLAB: { Icon: 'devicon-gitlab-plain', text: 'GitLab' },
  GRAFANA: { Icon: 'devicon-grafana-plain', text: 'Grafana' },
  GRAPHQL: { Icon: 'devicon-graphql-plain', text: 'GraphQL' },
  HADOOP: { Icon: 'devicon-hadoop-plain', text: 'Hadoop' },
  HTML: { Icon: 'devicon-html5-plain', text: 'HTML5' },
  JAVA: { Icon: 'devicon-java-plain', text: 'Java' },
  JAVASCRIPT: { Icon: 'devicon-javascript-plain', text: 'JavaScript' },
  JIRA: { Icon: 'devicon-jira-plain', text: 'Jira' },
  KAFKA: { Icon: 'devicon-apachekafka-original', text: 'Kafka' },
  KUBERNETES: { Icon: 'devicon-kubernetes-plain', text: 'Kubernetes' },
  LODASH: { Icon: 'devicon-lodash-plain', text: 'Lodash' },
  MATERIAL_UI: { Icon: 'devicon-materialui-plain', text: 'Material UI' },
  MY_SQL: { Icon: 'devicon-mysql-original', text: 'MySQL' },
  NEXTJS: { Icon: 'devicon-nextjs-plain', text: 'Next.js' },
  NODEJS: { Icon: 'devicon-nodejs-plain-wordmark', text: 'Node.js' },
  NOTION: { Icon: 'devicon-notion-plain', text: 'Notion' },
  NPM: { Icon: 'devicon-npm-original-wordmark', text: 'npm' },
  PERL: { Icon: 'devicon-perl-plain', text: 'Perl' },
  POSTGRESQL: { Icon: 'devicon-postgresql-plain', text: 'PostgreSQL' },
  POSTMAN: { Icon: 'devicon-postman-plain', text: 'Postman' },
  PYTHON: { Icon: 'devicon-python-plain', text: 'Python' },
  REACT: { Icon: 'devicon-react-original', text: 'React' },
  REACT_ROUTER: { Icon: 'devicon-reactrouter-plain', text: 'React Router' },
  REDIS: { Icon: 'devicon-redis-plain', text: 'Redis' },
  REDUX: { Icon: 'devicon-redux-original', text: 'Redux' },
  SENTRY: { Icon: 'devicon-sentry-original', text: 'Sentry' },
  SONARQUBE: { Icon: 'devicon-sonarqube-original', text: 'SonarQube' },
  SWAGGER: { Icon: 'devicon-swagger-plain', text: 'Swagger' },
  TERRAFORM: { Icon: 'devicon-terraform-plain', text: 'Terraform' },
  TYPESCRIPT: { Icon: 'devicon-typescript-plain', text: 'TypeScript' },
  VS_CODE: { Icon: 'devicon-vscode-plain', text: 'VS Code' },
};
